### ISSUE TITLE
[Vision] Checklist for making Cosmos React-agnostic

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#286]
### What's up?

Cosmos' mission to scale UI development by making it component-centric is more relevant than ever as web interfaces become increasingly complex by the year. Also growing is the number of UI libs & frameworks that sometimes have a similar API to that of React, while in other cases mirror it. Preact and Inferno are good examples, but we should also keep something like Vue components in mind.

One tendency is to port React projects to different libs, but we'd all benefit more by designing Cosmos in a way that separates React interfacing and allows the generic modules (component discovery, config, playground and others) to be pluggable into other component APIs. It's straightforward on a conceptual level, but there are many pieces that need adjusting to get this right.

### Mkay, tell me more...

This issue serves to:
1. Track the progress towards achieving this grand vision
2. Guide all future development to make sure all other initiatives converge into this vision

### CHECKLIST
- [x] `react-cosmos-utils` is  decoupled
- [x] `react-cosmos-voyager` (component & fixture file discovery) is decoupled 
- [x] `react-cosmos-config` is decoupled
- [x] `react-component-playground` is decoupled. This isn't intuitive as CP is a React component, but since the Loader is fully decoupled and loaded via iframe, the CP can continue to be React even if the loader renders something else
- [x] `react-querystring-router` same as above, it's React but it's not tied to the loader frame so it can remain so
- [ ] `react-cosmos` is where the bulk of the work goes:
  - [ ] Loader should have a lib agnostic root level component that communicates via postMessage with playground frame
  - [ ] Proxy API needs a simpler React agnostic contract defined, then have proxies split per lib (needs more thinking)
- [ ] `react-cosmos-webpack` [entrypoint](https://github.com/react-cosmos/react-cosmos/blob/ed8ef3e09645cd69d0086339ea6e169294bd4aef/packages/react-cosmos-webpack/src/entry.js) needs to be generalized (might come natural with changes from react-cosmos)

**Any help is appreciated!** – Here are a few things you can do:
- Point out missing (or invalid) items to make this list complete
- Bring any insights to the table regarding APIs of other component libs 
- Take this into consideration in your next contribution
- Come up with small non-breaking PRs that advance this vision

**Comment by skidding** [comment]
Closing this because the description is out of date and will confuse more than help. This idea has already been added as Cosmos' 3rd long term [goal](https://github.com/react-cosmos/react-cosmos/blob/master/CONTRIBUTING.md#goals) and I will likely open another thread after more important milestones have been achieved.
