### ISSUE TITLE
Data is reset when receiving the same dataURL

### ISSUE THREAD

**Issue by NiGhTTraX** [react-cosmos/react-cosmos#56]
## Need

``` gherkin
As a developer
I want to change props other than <dataUrl> on my component
And not fire new requests
And leave my data untouched
So that my component doesn't go through a 'loading' cycle.
```
## Deliverables

``` gherkin
Given I have a component
And it has the <dataUrl> prop set to <foo.com>
And I render the component
And it fetches data from <foo.com>
When I call <setProps> on the component
And pass it <dataUrl> to be <foo.com>
Then no requests are made to <foo.com>
And <state.data> is untouched.
```
## Solution

Remove the concept of `initialData`.
#### TODO
- [x] remove [getInitialData](https://github.com/skidding/cosmos/blob/master/mixins/data-fetch.js#L43-L48)
- [x] remove [resetting data](https://github.com/skidding/cosmos/blob/master/mixins/data-fetch.js#L50-L51)
- [x] remove [this](https://github.com/skidding/cosmos/blob/master/specs/mixin-data-fetch-spec.js#L42-L49) test
- [x] remove [this](https://github.com/skidding/cosmos/blob/master/specs/mixin-data-fetch-spec.js#L51-L58) test
- [x] use `getInitialState` [here](https://github.com/skidding/cosmos/blob/master/specs/mixin-data-fetch-spec.js#L61-L63)
- [x]  use `getInitialState` [here](https://github.com/skidding/cosmos/blob/master/specs/mixin-data-fetch-spec.js#L135-L137)
- [x] add a test for checking that no requests are made when receiving the same `dataUrl`
- [x] add a test for checking that `state.data` is left untouched when receiving the same `dataUrl`

@skidding
