### ISSUE TITLE
DataFetch events

### ISSUE THREAD

**Issue by NiGhTTraX** [react-cosmos/react-cosmos#58]
## Need

``` gherkin
As a developer
I want to know when data has started being fetched
And I want to know when data has finished being fetched
So that I can react to these events.
```
## Deliverables

``` gherkin
Given I have a component
And it includes the DataFetch mixin
When data hasn't started yet to be fetched
Then <state.fetchingData> will be <false>.
```

``` gherkin
Given I have a component
And it includes the DataFetch mixin
When data starts being fetched
Then <state.fetchingData> will be <true>.
```

``` gherkin
Given I have a component
And it includes the DataFetch mixin
When data finished being fetched
Then <state.fetchingData> will be <false>.
```
## Solution

Toggle an attribute on state whenever we start fetching data and whenever the request finishes.
#### TODO
- [x] tests
  - [x] at the start of a data fetch `state.fetchingData` is `true`
  - [x] at the end of a data fetch `state.fetchingData` is `false`
- [x] implementation
  - [x] toggle the state var before sending the request [here](https://github.com/skidding/cosmos/blob/master/mixins/data-fetch.js#L20)
  - [x] toggle the state var after receiving data [here](https://github.com/skidding/cosmos/blob/master/mixins/data-fetch.js#L36-L38)
  - [x] toggle the state var if the request errors [here](https://github.com/skidding/cosmos/blob/master/mixins/data-fetch.js#L31)
