### ISSUE TITLE
Implement a refresh method in the DataFetch mixin

### ISSUE THREAD

**Issue by NiGhTTraX** [react-cosmos/react-cosmos#63]
## Need

``` gherkin
As a developer
I need a way to re-fetch data from the server
So that I can get any updated data.
```
## Deliverables

The [DataFetch mixin](https://github.com/skidding/cosmos/blob/master/mixins/data-fetch.js) will expose a public refresh method.
## Solution

Rename the [resetData method](https://github.com/skidding/cosmos/blob/master/mixins/data-fetch.js#L39) to `refreshData`.
#### TODO
- [x] tests
  - [x] calling the refresh method will re-fetch data
- [x] implementation
  - [x] rename the method
  - [x] default the `props` argument to `this.props`
  - [x] move the [check](https://github.com/skidding/cosmos/blob/master/mixins/data-fetch.js#L46-L48) for `dataUrl` being the same into the `componentWillReceiveProps` method
  - [x] do not store `dataUrl` on the [instance](https://github.com/skidding/cosmos/blob/master/mixins/data-fetch.js#L49)
  - [x] update calls to it

@skidding
