### ISSUE TITLE
Speed up monorepo development

### ISSUE THREAD

**Issue by skidding** [react-cosmos/react-cosmos#786]
### What's up?

The RC monorepo has accumulated a lot of bloat over time. Simple operations like `yarn` or `yarn upgrade-interactive` can now take up to a few minutes. This is unproductive and frustrating.

![screenshot 2018-08-08 10 06 53](https://user-images.githubusercontent.com/250750/43823156-d81ae060-9af6-11e8-87a9-1eac64e5f22b.png)

On top of the time loss, there are also a lot of package warnings upon install that are distracting to say the least.

### Mkay, tell me more...

Here are a few things I want to do to make the monorepo lighter:
- [x] Try moving CI from Travis to CircleCI and compare the build times #800
- [x] Reduce the heavy E2E server tests (which run webpack fully) #801
- [x] Remove XO linter and use ESLint directly. This reduces a layer of abstration and a few dependencies. XO was very beneficial when ESLint didn't have the `overrides` option, but that has changed. In the meantime we added Prettier and Flow, which made ESLint's role smaller. Finally, a lot of the XO config is now disabling its rules so using it going forward feels counter intuitive. #802
- [x] Move the create-react-native-app example to a separate repo in the react-cosmos org. Either keep a simpler `react-native` example in the monorepo or none at all. Ever since we added React Native support the monorepo has become significantly slower. #804
- [ ] Move react-cosmos-apollo-proxy to a separate repo in the react-cosmos org, along with its example. It depends on a lot of packages that are GraphQL or Apollo specific, most of which evolve rapidly, resulting in a lot of dependency noise. Ie. `apollo-cache-inmemory apollo-client apollo-link apollo-link-http apollo-server-express graphql graphql-tag graphql-tools react-apollo`.
- [ ] Look for other deps to remove.
- [ ] Minimize duplicated deps (Eg. using separate versions of Lodash between packages).

**Comment by skidding** [comment]
Stopping here before this issue sucks too much time from me. Left Apollo proxy in the monorepo for now.

Moving to CircleCI sped up the CI a lot, and locally yarn installs faster without the whole Expo baggage. Cleaned up Jest and ESLint configs and merged two heavy tests. I'm happy for now.

On to features!

**Comment by michaelfarrell76** [comment]
upgrade-interactive sucks so much with the monorepo. did you end up finding anything better?

**Comment by skidding** [comment]
Works pretty well since I removed Expo from the monorepo and minimized deps. It's still clunky, though. Often you upgrade deps with `yarn upgrade-interactive` and then have to call `yarn` (install) again for node_modules to properly sync. Same when you add a dependency inside a package. `yarn add X` then `yarn` in the monorepo root. Speed is no longer a big issue on my current machine.

**Comment by michaelfarrell76** [comment]
ah interesting... I've been using `yarn upgrade-interactive --latest` which will actually do the installation + updating versions at the same time, but it goes through each package.json in the monorepo one by one installing the changes which is incredibly slow

**Comment by skidding** [comment]
> ...but it goes through each package.json in the monorepo one by one installing the changes which is incredibly slow

Oh yes, that is annoying.
